# Generated by Django 3.1.2 on 2021-12-14 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20211214_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'verbose_name': 'Container', 'verbose_name_plural': 'Containers'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='datalayer',
            options={'verbose_name': 'Datalayer', 'verbose_name_plural': 'Datalayers'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='environment',
            options={'verbose_name': 'Environment', 'verbose_name_plural': 'Environments'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Version', 'verbose_name_plural': 'Versions'},
        ),
        migrations.AddField(
            model_name='container',
            name='container',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='container',
            name='datalayer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container', to='document.datalayer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='datalayer',
            name='name',
            field=models.CharField(default='datalayer', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document', to='document.customer'),
        ),
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='environment',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environment', to='document.container'),
        ),
        migrations.AddField(
            model_name='environment',
            name='name',
            field=models.CharField(choices=[('P', 'production'), ('S', 'staging')], default='P', max_length=25),
        ),
        migrations.AddField(
            model_name='version',
            name='auditor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='version',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='version',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version', to='document.document'),
        ),
        migrations.AddField(
            model_name='version',
            name='note',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='version',
            name='version',
            field=models.CharField(blank=True, default='1.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentchaptertitle',
            name='chapter_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='document.chaptertitle'),
        ),
        migrations.AlterField(
            model_name='documentchaptertitle',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_title', to='document.document'),
        ),
    ]
