# Generated by Django 3.1.2 on 2021-12-21 13:59

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0016_auto_20211213_1717'),
        ('document', '0007_auto_20211216_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='eco_snippet_custom',
        ),
        migrations.RemoveField(
            model_name='section',
            name='eco_snippet_std',
        ),
        migrations.RemoveField(
            model_name='section',
            name='ga_event_snippet_custom',
        ),
        migrations.RemoveField(
            model_name='section',
            name='paragraph',
        ),
        migrations.CreateModel(
            name='SectionStd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('eco_snippet_std', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_std', to='snippet.ecommercesnippetstd')),
                ('ga_event_snippet_std', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_std', to='snippet.gaeventsnippetstd')),
                ('section', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_std', to='document.section')),
            ],
            options={
                'verbose_name': 'Section standard',
                'verbose_name_plural': 'Sections standard',
            },
        ),
        migrations.CreateModel(
            name='SectionCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('eco_snippet_custom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_custom', to='snippet.ecommercesnippetcustom')),
                ('ga_event_snippet_custom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_custom', to='snippet.gaeventsnippetcustom')),
                ('paragraph', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_custom', to='document.paragraph')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_custom', to='document.section')),
                ('section_std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_custom', to='document.sectionstd')),
            ],
            options={
                'verbose_name': 'Section custom',
                'verbose_name_plural': 'Sections custom',
            },
        ),
        migrations.CreateModel(
            name='DocumentChapterTitleParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('document_chapter_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.documentchaptertitle')),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.paragraph')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
