# Generated by Django 3.1.2 on 2021-12-21 14:12

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_auto_20211221_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChapterTitleParagraphSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('document_chapter_title_paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_chapter_title_paragraph_section', to='document.documentchaptertitleparagraph')),
                ('section_custom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_chapter_title_paragraph_section', to='document.sectioncustom')),
            ],
            options={
                'verbose_name': 'Document Chapter Title Paragraph Section',
                'verbose_name_plural': 'Document Chapter Title Paragraph Sections',
            },
        ),
    ]
