# Generated by Django 3.1.2 on 2021-12-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_documentchaptertitleparagraphsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentchaptertitle',
            options={'verbose_name': 'Document Chapter Title', 'verbose_name_plural': 'Document Chapter Titles'},
        ),
    ]
