# Generated by Django 3.1.2 on 2021-12-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0016_auto_20211213_1717'),
        ('document', '0010_auto_20211221_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='initial_snippet_custom',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snippet.initialsnippetcustom'),
        ),
    ]
