# Generated by Django 3.1.2 on 2021-12-21 18:19

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_datalayer_initial_snippet_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Chapter title',
                'verbose_name_plural': 'Chapter titles',
            },
        ),
        migrations.CreateModel(
            name='SectionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('action', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('priority', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Section template',
                'verbose_name_plural': 'Sections template',
            },
        ),
        migrations.CreateModel(
            name='SubChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Sub Chapter',
                'verbose_name_plural': 'Sub Chapters',
            },
        ),
        migrations.RemoveField(
            model_name='documentchaptertitle',
            name='chapter_title',
        ),
        migrations.RemoveField(
            model_name='documentchaptertitle',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentchaptertitleparagraph',
            name='document_chapter_title',
        ),
        migrations.RemoveField(
            model_name='documentchaptertitleparagraph',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='documentchaptertitleparagraphsection',
            name='document_chapter_title_paragraph',
        ),
        migrations.RemoveField(
            model_name='documentchaptertitleparagraphsection',
            name='section_custom',
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='chapter_title',
        ),
        migrations.RemoveField(
            model_name='sectioncustom',
            name='eco_snippet_custom',
        ),
        migrations.RemoveField(
            model_name='sectioncustom',
            name='ga_event_snippet_custom',
        ),
        migrations.RemoveField(
            model_name='sectioncustom',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='sectioncustom',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sectioncustom',
            name='section_std',
        ),
        migrations.RemoveField(
            model_name='sectionstd',
            name='eco_snippet_std',
        ),
        migrations.RemoveField(
            model_name='sectionstd',
            name='ga_event_snippet_std',
        ),
        migrations.RemoveField(
            model_name='sectionstd',
            name='section',
        ),
        migrations.RenameField(
            model_name='datalayer',
            old_name='initial_snippet_custom',
            new_name='initial_snippet',
        ),
    ]
