# Generated by Django 3.1.2 on 2021-12-21 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0017_auto_20211221_1819'),
        ('document', '0012_auto_20211221_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='eco_snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='snippet.ecommercesnippet'),
        ),
        migrations.AddField(
            model_name='section',
            name='ga_snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='snippet.gasnippet'),
        ),
        migrations.AlterField(
            model_name='section',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='section',
            name='priority',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ChapterTitle',
        ),
        migrations.DeleteModel(
            name='DocumentChapterTitle',
        ),
        migrations.DeleteModel(
            name='DocumentChapterTitleParagraph',
        ),
        migrations.DeleteModel(
            name='DocumentChapterTitleParagraphSection',
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
        migrations.DeleteModel(
            name='SectionCustom',
        ),
        migrations.DeleteModel(
            name='SectionStd',
        ),
        migrations.AddField(
            model_name='sectiontemplate',
            name='eco_snippet_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_template', to='snippet.ecommercesnippettemplate'),
        ),
        migrations.AddField(
            model_name='sectiontemplate',
            name='ga_snippet_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_template', to='snippet.gasnippettemplate'),
        ),
    ]
