# Generated by Django 3.1.2 on 2021-12-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_auto_20211222_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='document',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.document'),
        ),
    ]
