# Generated by Django 3.1.2 on 2021-12-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0019_auto_20211226_1251'),
        ('document', '0015_datalayer_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontemplate',
            name='eco_snippet_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_template', to='snippet.ecommercesnippettemplate'),
        ),
        migrations.AlterField(
            model_name='sectiontemplate',
            name='ga_snippet_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_template', to='snippet.gasnippettemplate'),
        ),
    ]
