# Generated by Django 3.1.2 on 2021-12-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_auto_20211226_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document.document'),
        ),
        migrations.AddField(
            model_name='section',
            name='sub_chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document.subchapter'),
        ),
        migrations.AddField(
            model_name='subchapter',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document.chapter'),
        ),
    ]
