# Generated by Django 3.1.2 on 2021-12-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0017_auto_20211227_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='document.document'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='document.subchapter'),
        ),
        migrations.AlterField(
            model_name='subchapter',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_chapter', to='document.chapter'),
        ),
    ]
