# Generated by Django 3.1.2 on 2021-12-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0018_auto_20211227_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='icon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
