# Generated by Django 3.1.2 on 2022-01-03 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0024_auto_20220103_0903'),
        ('document', '0019_auto_20211227_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='ga4_eco_snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='snippet.ecommercesnippetga4'),
        ),
        migrations.AddField(
            model_name='sectiontemplate',
            name='ga4_eco_snippet_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_template', to='snippet.ecommercesnippettemplatega4'),
        ),
    ]
