# Generated by Django 3.1.2 on 2022-01-05 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0020_auto_20220103_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subchapter',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subChapter', to='document.chapter'),
        ),
    ]
