# Generated by Django 3.1.2 on 2022-01-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0021_auto_20220105_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='category',
        ),
    ]
