# Generated by Django 3.1.2 on 2022-01-11 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0025_auto_20220107_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container', to='document.document'),
        ),
    ]
