# Generated by Django 3.1.2 on 2022-01-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0028_auto_20220111_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectiontemplate',
            options={'ordering': ['-pk'], 'verbose_name': 'Section template', 'verbose_name_plural': 'Sections template'},
        ),
    ]
