# Generated by Django 3.1.2 on 2022-01-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0029_auto_20220113_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-pk'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
    ]
