# Generated by Django 3.1.2 on 2022-02-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0030_auto_20220113_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='ga_snippet',
        ),
    ]
