# Generated by Django 3.1.2 on 2022-02-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0031_remove_section_ga_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='document.image'),
        ),
    ]
