# Generated by Django 3.1.2 on 2022-02-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0032_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='page_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
