# Generated by Django 3.1.2 on 2022-02-24 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0033_image_page_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container', to='document.document'),
        ),
        migrations.AlterField(
            model_name='datalayer',
            name='document',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datalayer', to='document.document'),
        ),
    ]
