# Generated by Django 3.1.2 on 2021-12-06 11:26

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('currency_code', models.CharField(blank=True, max_length=255)),
                ('_id', models.CharField(max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('variant', models.CharField(blank=True, max_length=255)),
                ('list', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('quantity', models.IntegerField(blank=True)),
                ('creative', models.CharField(blank=True, max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('revenue', models.CharField(blank=True, max_length=255)),
                ('tax', models.CharField(blank=True, max_length=255)),
                ('shipping', models.CharField(blank=True, max_length=255)),
                ('coupon', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Ecommerce snippet',
                'verbose_name_plural': 'Ecommerce snippets',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GAeventSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('event_category', models.CharField(blank=True, max_length=255)),
                ('event_action', models.CharField(blank=True, max_length=255)),
                ('event_label', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Ga event snippet',
                'verbose_name_plural': 'Ga event snippets',
            },
        ),
        migrations.CreateModel(
            name='InitialSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='variable',
            options={'verbose_name': 'Variable', 'verbose_name_plural': 'Variables'},
        ),
        migrations.AlterModelOptions(
            name='variablevalue',
            options={'verbose_name': 'Variable Value', 'verbose_name_plural': 'Variable Values'},
        ),
        migrations.RemoveField(
            model_name='variablevalue',
            name='variable',
        ),
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(max_length=255, null=None),
        ),
        migrations.AlterField(
            model_name='variabletype',
            name='name',
            field=models.CharField(max_length=255, null=None),
        ),
        migrations.AlterField(
            model_name='variablevalue',
            name='condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variablevalue',
            name='name',
            field=models.CharField(max_length=255, null=None),
        ),
        migrations.CreateModel(
            name='SnippetVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('eco_snippet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet_variable', to='base.ecommercesnippet')),
                ('ga_event_snippet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet_variable', to='base.gaeventsnippet')),
                ('init_snippet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet_variable', to='base.initialsnippet')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippet_variable', to='base.variable')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('eco_snippet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet', to='base.ecommercesnippet')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snippet', to='base.event')),
                ('ga_event_snippet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet', to='base.gaeventsnippet')),
                ('init_snippet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet', to='base.initialsnippet')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snippet', to='base.section')),
            ],
            options={
                'verbose_name': 'Snippet',
                'verbose_name_plural': 'Snippets',
            },
        ),
        migrations.CreateModel(
            name='CustomVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_variable', to='base.variable')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('is_dimension', models.BooleanField(default=False)),
                ('is_metric', models.BooleanField(default=False)),
                ('eco_snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field', to='base.ecommercesnippet')),
            ],
            options={
                'verbose_name': 'Custom field',
                'verbose_name_plural': 'Custom fields',
            },
        ),
        migrations.CreateModel(
            name='CommonVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_variable', to='base.variable')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='variablevalue',
            name='common_variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_value', to='base.commonvariable'),
        ),
        migrations.AddField(
            model_name='variablevalue',
            name='custom_variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_value', to='base.customvariable'),
        ),
    ]
