# Generated by Django 3.1.2 on 2021-12-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211206_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabletype',
            name='priority',
            field=models.CharField(default='Alta', max_length=255, null=None),
        ),
        migrations.AddField(
            model_name='variabletype',
            name='scope',
            field=models.CharField(default='Hit', max_length=255, null=None),
        ),
        migrations.AlterField(
            model_name='variabletype',
            name='name',
            field=models.CharField(default='dataLayer', max_length=255, null=None),
        ),
    ]
