# Generated by Django 3.1.2 on 2021-12-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211206_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablevalue',
            name='variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_value', to='base.variable'),
        ),
    ]
