# Generated by Django 3.1.2 on 2021-12-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211207_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippetvariable',
            old_name='eco_snippet',
            new_name='eco_snippet_std',
        ),
        migrations.RenameField(
            model_name='snippetvariable',
            old_name='ga_event_snippet',
            new_name='ga_event_snippet_std',
        ),
    ]
