# Generated by Django 3.1.2 on 2021-12-10 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0002_auto_20211210_0904'),
        ('base', '0008_auto_20211210_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippetvariable',
            name='eco_snippet_custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet_variable', to='snippet.ecommercesnippetcustom'),
        ),
        migrations.AddField(
            model_name='snippetvariable',
            name='ga_event_snippet_custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet_variable', to='snippet.gaeventsnippetcustom'),
        ),
        migrations.AlterField(
            model_name='variabletype',
            name='priority',
            field=models.CharField(max_length=255, null=None),
        ),
        migrations.AlterField(
            model_name='variabletype',
            name='reference',
            field=models.CharField(max_length=255, null=None),
        ),
        migrations.AlterField(
            model_name='variabletype',
            name='scope',
            field=models.CharField(max_length=255, null=None),
        ),
        migrations.AlterField(
            model_name='variablevalue',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_value', to='base.variable'),
        ),
    ]
