# Generated by Django 3.1.2 on 2021-12-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0016_auto_20211213_1717'),
        ('base', '0009_auto_20211210_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='initial_snippet_custom',
            field=models.ManyToManyField(to='snippet.InitialSnippetCustom'),
        ),
    ]
