# Generated by Django 3.1.2 on 2021-12-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_variable_initial_snippet_custom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippetvariable',
            old_name='init_snippet',
            new_name='initial_snippet',
        ),
        migrations.RemoveField(
            model_name='snippetvariable',
            name='eco_snippet_custom',
        ),
        migrations.RemoveField(
            model_name='snippetvariable',
            name='eco_snippet_std',
        ),
        migrations.RemoveField(
            model_name='snippetvariable',
            name='ga_event_snippet_custom',
        ),
        migrations.RemoveField(
            model_name='snippetvariable',
            name='ga_event_snippet_std',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='initial_snippet_custom',
        ),
    ]
