# Generated by Django 3.1.2 on 2021-12-21 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0017_auto_20211221_1819'),
        ('base', '0011_auto_20211221_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippetvariable',
            name='eco_snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet_variable', to='snippet.ecommercesnippet'),
        ),
        migrations.AddField(
            model_name='snippetvariable',
            name='eco_snippet_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet_variable', to='snippet.ecommercesnippettemplate'),
        ),
        migrations.AddField(
            model_name='snippetvariable',
            name='ga_snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet_variable', to='snippet.gasnippet'),
        ),
        migrations.AddField(
            model_name='snippetvariable',
            name='ga_snippet_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet_variable', to='snippet.gasnippettemplate'),
        ),
        migrations.AddField(
            model_name='variable',
            name='initial_snippet',
            field=models.ManyToManyField(to='snippet.InitialSnippet'),
        ),
    ]
