# Generated by Django 3.1.2 on 2022-01-12 16:50

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0030_auto_20220112_1650'),
        ('base', '0014_auto_20220103_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialSnippetVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('initial_snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_snippet_variable', to='snippet.initialsnippet')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_snippet_variable', to='base.variabletype')),
            ],
            options={
                'verbose_name': 'Initial snippet variable',
                'verbose_name_plural': 'Initial snippet variables',
            },
        ),
        migrations.CreateModel(
            name='InitialSnippetVariableValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('initial_snippet_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_snippet_variable_value', to='base.initialsnippetvariable')),
            ],
            options={
                'verbose_name': 'Initial snippet variable value',
                'verbose_name_plural': 'Initial snippet variable values',
            },
        ),
    ]
