# Generated by Django 3.1.2 on 2022-01-13 17:12

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0030_auto_20220113_0942'),
        ('base', '0015_initialsnippetvariable_initialsnippetvariablevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_variable', to='document.document')),
                ('type', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_variable', to='base.variabletype')),
            ],
            options={
                'verbose_name': 'Document variable',
                'verbose_name_plural': 'Document variables',
            },
        ),
        migrations.AlterField(
            model_name='initialsnippetvariable',
            name='type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_snippet_variable', to='base.variabletype'),
        ),
        migrations.CreateModel(
            name='DocumentVariableValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('document_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_variable_value', to='base.documentvariable')),
            ],
            options={
                'verbose_name': 'Document variable value',
                'verbose_name_plural': 'Document variable values',
            },
        ),
    ]
