# Generated by Django 3.1.2 on 2022-01-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20220113_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='initial_snippet',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='is_custom',
        ),
    ]
