# Generated by Django 3.1.2 on 2022-01-17 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0031_auto_20220117_2204'),
        ('base', '0017_auto_20220117_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialsnippetvariable',
            name='initial_snippet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippet.initialsnippet'),
        ),
        migrations.AlterField(
            model_name='initialsnippetvariable',
            name='type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.variabletype'),
        ),
        migrations.AlterField(
            model_name='initialsnippetvariablevalue',
            name='initial_snippet_variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.initialsnippetvariable'),
        ),
    ]
