# Generated by Django 3.1.2 on 2022-01-18 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0031_auto_20220117_2204'),
        ('base', '0018_auto_20220117_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentvariable',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='initialsnippetvariable',
            name='is_template',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='is_template',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='initialsnippetvariable',
            name='initial_snippet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_snippet_variable', to='snippet.initialsnippet'),
        ),
        migrations.AlterField(
            model_name='initialsnippetvariablevalue',
            name='initial_snippet_variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_snippet_variable_value', to='base.initialsnippetvariable'),
        ),
    ]
