# Generated by Django 3.1.2 on 2022-01-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20220118_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialsnippetvariable',
            name='old_idx',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
