# Generated by Django 3.1.2 on 2022-01-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20220118_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialsnippetvariablevalue',
            name='old_idx',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
