# Generated by Django 3.1.2 on 2022-02-02 13:13

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0034_auto_20220201_1119'),
        ('base', '0022_initialsnippetvariablevalue_old_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='GASnippetVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('id_template', models.BooleanField(default=False)),
                ('old_idx', models.IntegerField(blank=True, null=True)),
                ('ga_snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_snippet_variable', to='snippet.gasnippet')),
            ],
            options={
                'verbose_name': 'GA snippet variable',
                'verbose_name_plural': 'GA snippet variables',
            },
        ),
        migrations.CreateModel(
            name='GASnippetVariableValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('ga_snippet_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_snippet_variable_value', to='base.gasnippetvariable')),
            ],
            options={
                'verbose_name': 'GA snippet variable value',
                'verbose_name_plural': 'GA snippet variable values',
            },
        ),
        migrations.DeleteModel(
            name='SnippetVariable',
        ),
    ]
