# Generated by Django 3.1.2 on 2022-02-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20220202_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablevalue',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_value', to='base.variable'),
        ),
    ]
