# Generated by Django 3.1.2 on 2022-03-05 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20220224_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentvariable',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_variable', to='base.variabletype'),
        ),
    ]
