# Generated by Django 3.1.2 on 2022-03-28 08:48

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0041_customfield_document'),
        ('base', '0028_auto_20220305_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceSnippetVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('is_template', models.BooleanField(default=False)),
                ('old_idx', models.IntegerField(blank=True, null=True)),
                ('eco_snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eco_snippet_variable', to='snippet.ecommercesnippet')),
                ('eco_snippet_ga4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eco_snippet_variable', to='snippet.ecommercesnippetga4')),
            ],
            options={
                'verbose_name': 'Ecommerce snippet variable',
                'verbose_name_plural': 'Ecommerce snippet variables',
            },
        ),
        migrations.CreateModel(
            name='EcommerceSnippetVariableValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('eco_snippet_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eco_snippet_variable_value', to='base.ecommercesnippetvariable')),
            ],
            options={
                'verbose_name': 'Ecommerce snippet variable value',
                'verbose_name_plural': 'Ecommerce snippet variable values',
            },
        ),
    ]
