# Generated by Django 3.1.2 on 2022-03-28 13:46

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0042_auto_20220328_0848'),
        ('base', '0029_ecommercesnippetvariable_ecommercesnippetvariablevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceSnippetVariableTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('old_idx', models.IntegerField(blank=True, null=True)),
                ('eco_snippet_ga4_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eco_snippet_variable_template', to='snippet.ecommercesnippettemplatega4')),
                ('eco_snippet_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eco_snippet_variable_template', to='snippet.ecommercesnippettemplate')),
            ],
            options={
                'verbose_name': 'Ecommerce snippet variable template',
                'verbose_name_plural': 'Ecommerce snippet variables template',
            },
        ),
        migrations.CreateModel(
            name='EcommerceSnippetVariableTemplateValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('eco_snippet_variable_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eco_snippet_variable_template_value', to='base.ecommercesnippetvariabletemplate')),
            ],
            options={
                'verbose_name': 'Ecommerce snippet variable template value',
                'verbose_name_plural': 'Ecommerce snippet variable template values',
            },
        ),
    ]
