# Generated by Django 3.1.2 on 2022-03-29 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0043_auto_20220328_1352'),
        ('base', '0031_auto_20220328_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercesnippetvariabletemplate',
            name='eco_snippet_ga4_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eco_snippet_variable_template', to='snippet.ecommercesnippettemplatega4'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippetvariabletemplate',
            name='eco_snippet_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eco_snippet_variable_template', to='snippet.ecommercesnippettemplate'),
        ),
    ]
