# Generated by Django 3.1.2 on 2021-12-10 09:04

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20211210_0904'),
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InitialSnippet',
            new_name='InitialSnippetCustom',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='eco_snippet',
            new_name='eco_snippet_std',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='ga_event_snippet',
            new_name='ga_event_snippet_std',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='eco_snippet',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='name',
        ),
        migrations.AddField(
            model_name='customfield',
            name='initial_snippet_custom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field', to='snippet.initialsnippetcustom'),
        ),
        migrations.RenameModel(
            old_name='EcommerceSnippet',
            new_name='EcommerceSnippetStd',
        ),
        migrations.RenameModel(
            old_name='GAeventSnippet',
            new_name='GAeventSnippetStd',
        ),
        migrations.CreateModel(
            name='GAeventSnippetCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('ga_event_snippet_std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_event_snippet_custom', to='snippet.gaeventsnippetstd')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EcommerceSnippetCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('eco_snippet_std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eco_snippet_custom', to='snippet.ecommercesnippetstd')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customfield',
            name='eco_snippet_custom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field', to='snippet.ecommercesnippetcustom'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='ga_event_snippet_custom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field', to='snippet.gaeventsnippetcustom'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='eco_snippet_custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet', to='snippet.ecommercesnippetcustom'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='ga_event_snippet_custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet', to='snippet.gaeventsnippetcustom'),
        ),
    ]
