# Generated by Django 3.1.2 on 2021-12-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0003_gaeventsnippetstd_event_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecommercesnippetstd',
            options={'verbose_name': 'Ecommerce snippet std', 'verbose_name_plural': 'Ecommerce snippets std'},
        ),
        migrations.AlterModelOptions(
            name='gaeventsnippetstd',
            options={'verbose_name': 'GA event snippet std', 'verbose_name_plural': 'GA event snippets std'},
        ),
    ]
