# Generated by Django 3.1.2 on 2021-12-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0004_auto_20211210_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecommercesnippetcustom',
            options={'verbose_name': 'Ecommerce snippet custom', 'verbose_name_plural': 'Ecommerce snippets custom'},
        ),
        migrations.AlterModelOptions(
            name='gaeventsnippetcustom',
            options={'verbose_name': 'GA event snippet custom', 'verbose_name_plural': 'GA event snippets custom'},
        ),
        migrations.AlterModelOptions(
            name='initialsnippetcustom',
            options={'verbose_name': 'Initial snippet custom', 'verbose_name_plural': 'Initial snippets custom'},
        ),
    ]
