# Generated by Django 3.1.2 on 2021-12-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0005_auto_20211210_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaeventsnippetstd',
            name='event_id',
        ),
        migrations.AddField(
            model_name='gaeventsnippetcustom',
            name='event_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
