# Generated by Django 3.1.2 on 2021-12-10 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0006_auto_20211210_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='eco_snippet_custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field', to='snippet.ecommercesnippetcustom'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='ga_event_snippet_custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field', to='snippet.gaeventsnippetcustom'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='initial_snippet_custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field', to='snippet.initialsnippetcustom'),
        ),
    ]
