# Generated by Django 3.1.2 on 2021-12-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0007_auto_20211210_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialsnippetcustom',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='initialsnippetcustom',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
