# Generated by Django 3.1.2 on 2021-12-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0009_auto_20211211_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name': 'Event Category', 'verbose_name_plural': 'Event Categories'},
        ),
    ]
