# Generated by Django 3.1.2 on 2021-12-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0010_auto_20211211_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='category',
            field=models.CharField(choices=[('Ecommerce', 'Ecommerce'), ('Google Analytics', 'Google Analytics'), ('Custom', 'Custom')], default='Custom', max_length=255),
        ),
    ]
