# Generated by Django 3.1.2 on 2021-12-13 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0011_auto_20211211_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='eco_snippet_custom',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='eco_snippet_std',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='event',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='ga_event_snippet_custom',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='ga_event_snippet_std',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='init_snippet',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='section',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.RenameField(
            model_name='gaeventsnippetcustom',
            old_name='event_id',
            new_name='event_id_custom',
        ),
        migrations.AddField(
            model_name='ecommercesnippetcustom',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecommerce_snippet_custom', to='snippet.event'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetstd',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecommerce_snippet_std', to='snippet.event'),
        ),
        migrations.AddField(
            model_name='gaeventsnippetcustom',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ga_event_snippet_custom', to='snippet.event'),
        ),
        migrations.AddField(
            model_name='gaeventsnippetstd',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ga_event_snippet_std', to='snippet.event'),
        ),
        migrations.AddField(
            model_name='initialsnippetcustom',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_snippet_custom', to='snippet.event'),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
