# Generated by Django 3.1.2 on 2021-12-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0012_auto_20211213_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcategory',
            old_name='category',
            new_name='name',
        ),
    ]
