# Generated by Django 3.1.2 on 2021-12-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0013_auto_20211213_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaeventsnippetcustom',
            name='event',
        ),
    ]
