# Generated by Django 3.1.2 on 2021-12-21 18:19

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_auto_20211221_1819'),
        ('base', '0011_auto_20211221_1819'),
        ('snippet', '0016_auto_20211213_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('currency_code', models.CharField(blank=True, max_length=255)),
                ('_id', models.CharField(max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('variant', models.CharField(blank=True, max_length=255)),
                ('list', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('quantity', models.IntegerField(blank=True)),
                ('creative', models.CharField(blank=True, max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('revenue', models.CharField(blank=True, max_length=255)),
                ('tax', models.CharField(blank=True, max_length=255)),
                ('shipping', models.CharField(blank=True, max_length=255)),
                ('coupon', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecommerce_snippet', to='snippet.event')),
            ],
            options={
                'verbose_name': 'Ecommerce snippet',
                'verbose_name_plural': 'Ecommerce snippets',
            },
        ),
        migrations.CreateModel(
            name='EcommerceSnippetTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('currency_code', models.CharField(blank=True, max_length=255)),
                ('_id', models.CharField(max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('variant', models.CharField(blank=True, max_length=255)),
                ('list', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('quantity', models.IntegerField(blank=True)),
                ('creative', models.CharField(blank=True, max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('revenue', models.CharField(blank=True, max_length=255)),
                ('tax', models.CharField(blank=True, max_length=255)),
                ('shipping', models.CharField(blank=True, max_length=255)),
                ('coupon', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecommerce_snippet_template', to='snippet.event')),
            ],
            options={
                'verbose_name': 'Ecommerce snippet template',
                'verbose_name_plural': 'Ecommerce snippets template',
            },
        ),
        migrations.CreateModel(
            name='GASnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('event_id_custom', models.CharField(blank=True, max_length=100)),
                ('event_category', models.CharField(blank=True, max_length=255)),
                ('event_action', models.CharField(blank=True, max_length=255)),
                ('event_label', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ga_snippet', to='snippet.event')),
            ],
            options={
                'verbose_name': 'GA Snippet',
                'verbose_name_plural': 'GA snippets',
            },
        ),
        migrations.CreateModel(
            name='GASnippetTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('event_category', models.CharField(blank=True, max_length=255)),
                ('event_action', models.CharField(blank=True, max_length=255)),
                ('event_label', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ga_snippet_template', to='snippet.event')),
            ],
            options={
                'verbose_name': 'GA event snippet template',
                'verbose_name_plural': 'GA event snippets template',
            },
        ),
        migrations.RenameModel(
            old_name='InitialSnippetCustom',
            new_name='InitialSnippet',
        ),
        migrations.RemoveField(
            model_name='ecommercesnippetstd',
            name='event',
        ),
        migrations.RemoveField(
            model_name='gaeventsnippetcustom',
            name='ga_event_snippet_std',
        ),
        migrations.RemoveField(
            model_name='gaeventsnippetstd',
            name='event',
        ),
        migrations.AlterModelOptions(
            name='initialsnippet',
            options={'verbose_name': 'Initial snippet', 'verbose_name_plural': 'Initial snippets'},
        ),
        migrations.RenameField(
            model_name='customfield',
            old_name='initial_snippet_custom',
            new_name='initial_snippet',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='eco_snippet_custom',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='ga_event_snippet_custom',
        ),
        migrations.DeleteModel(
            name='EcommerceSnippetCustom',
        ),
        migrations.DeleteModel(
            name='EcommerceSnippetStd',
        ),
        migrations.DeleteModel(
            name='GAeventSnippetCustom',
        ),
        migrations.DeleteModel(
            name='GAeventSnippetStd',
        ),
        migrations.AddField(
            model_name='customfield',
            name='eco_snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field', to='snippet.ecommercesnippet'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='ga_snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field', to='snippet.gasnippet'),
        ),
    ]
