# Generated by Django 3.1.2 on 2021-12-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0017_auto_20211221_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasnippettemplate',
            options={'verbose_name': 'GA snippet template', 'verbose_name_plural': 'GA snippets template'},
        ),
    ]
