# Generated by Django 3.1.2 on 2021-12-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0018_auto_20211222_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercesnippettemplate',
            name='price',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
