# Generated by Django 3.1.2 on 2021-12-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0019_auto_20211226_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercesnippettemplate',
            name='quantity',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
