# Generated by Django 3.1.2 on 2021-12-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0020_auto_20211226_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercesnippet',
            name='price',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ecommercesnippet',
            name='quantity',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
