# Generated by Django 3.1.2 on 2021-12-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0021_auto_20211226_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecommercesnippet',
            old_name='_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='ecommercesnippettemplate',
            old_name='_id',
            new_name='item_id',
        ),
    ]
