# Generated by Django 3.1.2 on 2022-01-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0022_auto_20211226_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-pk'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplate',
            name='snippet_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gasnippettemplate',
            name='snippet_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
