# Generated by Django 3.1.2 on 2022-01-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0024_auto_20220103_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercesnippetga4',
            name='discount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='discount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
