# Generated by Django 3.1.2 on 2022-01-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0025_auto_20220103_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercesnippetga4',
            name='discount',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ecommercesnippetga4',
            name='index',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ecommercesnippetga4',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ecommercesnippetga4',
            name='quantity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ecommercesnippetga4',
            name='shipping',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ecommercesnippetga4',
            name='tax',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ecommercesnippetga4',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='discount',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='index',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='quantity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='shipping',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='tax',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
