# Generated by Django 3.1.2 on 2022-01-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0026_auto_20220103_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercesnippetga4',
            name='item_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ecommercesnippetga4',
            name='item_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='item_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='item_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
