# Generated by Django 3.1.2 on 2022-01-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0027_auto_20220103_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecommercesnippettemplatega4',
            options={'ordering': ['-pk'], 'verbose_name': 'Ecommerce snippet template GA4', 'verbose_name_plural': 'Ecommerce snippets template GA4'},
        ),
        migrations.AlterModelOptions(
            name='gasnippettemplate',
            options={'ordering': ['-pk'], 'verbose_name': 'GA snippet template', 'verbose_name_plural': 'GA snippets template'},
        ),
    ]
