# Generated by Django 3.1.2 on 2022-01-17 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0030_auto_20220112_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='initial_snippet',
        ),
        migrations.AlterField(
            model_name='initialsnippet',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_snippet', to='snippet.event'),
        ),
    ]
