# Generated by Django 3.1.2 on 2022-01-24 08:26

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0031_auto_20220117_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldOldIdx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name_old_idx', models.IntegerField(blank=True, null=True)),
                ('value_old_idx', models.IntegerField(blank=True, null=True)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_old_idx', to='snippet.customfield')),
            ],
            options={
                'verbose_name': 'Custom field old idx',
                'verbose_name_plural': 'Custom field old idxs',
            },
        ),
    ]
