# Generated by Django 3.1.2 on 2022-02-01 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0030_auto_20220113_0942'),
        ('snippet', '0033_auto_20220124_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasnippet',
            name='datalayer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ga_snippet', to='document.datalayer'),
        ),
        migrations.AddField(
            model_name='gasnippet',
            name='snippet_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
