# Generated by Django 3.1.2 on 2022-02-02 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20220202_1313'),
        ('snippet', '0034_auto_20220201_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasnippet',
            name='event_action_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_action_variable', to='base.gasnippetvariable'),
        ),
        migrations.AddField(
            model_name='gasnippet',
            name='event_category_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_category_variable', to='base.gasnippetvariable'),
        ),
        migrations.AddField(
            model_name='gasnippet',
            name='event_label_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_label_variable', to='base.gasnippetvariable'),
        ),
    ]
