# Generated by Django 3.1.2 on 2022-02-04 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20220202_1757'),
        ('snippet', '0035_auto_20220202_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='value_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_value', to='base.gasnippetvariable'),
        ),
    ]
