# Generated by Django 3.1.2 on 2022-02-08 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0031_remove_section_ga_snippet'),
        ('snippet', '0037_auto_20220207_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasnippet',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ga_snippet', to='document.section'),
        ),
        migrations.DeleteModel(
            name='GASnippetSection',
        ),
    ]
