# Generated by Django 3.1.2 on 2022-03-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0039_auto_20220208_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
