# Generated by Django 3.1.2 on 2022-03-07 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0034_auto_20220224_1032'),
        ('snippet', '0040_auto_20220301_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field', to='document.document'),
        ),
    ]
