# Generated by Django 3.1.2 on 2022-03-28 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_ecommercesnippetvariable_ecommercesnippetvariablevalue'),
        ('snippet', '0041_customfield_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercesnippet',
            name='affiliation_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_affiliation_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippet',
            name='brand_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_brand_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippet',
            name='category_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_category_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippet',
            name='coupon_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_coupon_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippet',
            name='creative_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_creative_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippet',
            name='currency_code_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_currency_code_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippet',
            name='item_id_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_item_id_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippet',
            name='list_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_list_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippet',
            name='name_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_name_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippet',
            name='position_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_position_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippet',
            name='price_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_price_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippet',
            name='quantity_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_quantity_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippet',
            name='revenue_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_revenue_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippet',
            name='shipping_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_shipping_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippet',
            name='snippet_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ecommercesnippet',
            name='tax_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_tax_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippet',
            name='variant_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_variant_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='affiliation_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_affiliation_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='coupon_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_coupon_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='creative_name_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_creative_name_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='creative_slot_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_creative_slot_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='currency_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_currency_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='discount_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_discount_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='index_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_index_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='item_brand_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_item_brand_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='item_category2_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_item_category2_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='item_category3_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_item_category3_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='item_category4_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_item_category4_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='item_category_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_item_category_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='item_id_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_item_id_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='item_list_id_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_item_list_id_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='item_list_name_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_item_list_name_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='item_name_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_item_name_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='item_variant_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_item_variant_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='location_id_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_location_id_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='payment_type_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_payment_type_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='price_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_price_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='promotion_id_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_promotion_id_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='promotion_name_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_promotion_name_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='quantity_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_quantity_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='shipping_tier_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_shipping_tier_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='shipping_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_shipping_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='tax_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_tax_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='transaction_id_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_transaction_id_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippetga4',
            name='value_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eco_ga4_value_variable', to='base.ecommercesnippetvariable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplate',
            name='affiliation_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_affiliation_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplate',
            name='brand_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_brand_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplate',
            name='category_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_category_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplate',
            name='coupon_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_coupon_vairable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplate',
            name='creative_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_creative_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplate',
            name='currency_code_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_currency_code_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplate',
            name='item_id_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_item_id_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplate',
            name='list_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_list_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplate',
            name='name_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_name_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplate',
            name='position_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_position_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplate',
            name='price_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_price_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplate',
            name='quantity_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_quantity_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplate',
            name='revenue_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_revenue_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplate',
            name='shipping_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_shipping_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplate',
            name='tax_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_tax_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplate',
            name='variant_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_variant_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='affiliation_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_affiliation_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='coupon_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_coupon_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='creative_name_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_creative_name_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='creative_slot_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_creative_slot_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='currency_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_currency_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='discount_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_discount_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='index_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_index_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='item_brand_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_brand_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='item_category2_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_category2_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='item_category3_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_category3_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='item_category4_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_category4_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='item_category_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_category_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='item_id_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_id_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='item_list_id_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_list_id_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='item_list_name_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_list_name_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='item_name_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_name_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='item_variant_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_variant_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='location_id_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_location_id_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='payment_type_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_payment_type_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='price_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_price_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='promotion_id_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_promotion_id_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='promotion_name_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_promotion_name_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='quantity_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_quantity_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='shipping_tier_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_shipping_tier_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='shipping_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_shipping_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='tax_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_tax_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='transaction_id_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_transaction_id_variable', to='base.variable'),
        ),
        migrations.AddField(
            model_name='ecommercesnippettemplatega4',
            name='value_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_value_variable', to='base.variable'),
        ),
    ]
