# Generated by Django 3.1.2 on 2022-03-28 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_ecommercesnippetvariabletemplate_ecommercesnippetvariabletemplatevalue'),
        ('snippet', '0042_auto_20220328_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercesnippettemplate',
            name='affiliation_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_affiliation_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplate',
            name='brand_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_brand_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplate',
            name='category_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_category_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplate',
            name='coupon_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_coupon_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplate',
            name='creative_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_creative_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplate',
            name='currency_code_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_currency_code_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplate',
            name='item_id_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_item_id_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplate',
            name='list_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_list_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplate',
            name='name_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_name_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplate',
            name='position_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_position_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplate',
            name='price_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_price_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplate',
            name='quantity_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_quantity_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplate',
            name='revenue_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_revenue_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplate',
            name='shipping_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_shipping_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplate',
            name='tax_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_tax_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplate',
            name='variant_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_variant_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='affiliation_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_affiliation_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='coupon_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_coupon_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='creative_name_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_creative_name_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='creative_slot_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_creative_slot_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='currency_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_currency_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='discount_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_discount_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='index_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_index_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='item_brand_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_brand_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='item_category2_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_category2_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='item_category3_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_category3_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='item_category4_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_category4_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='item_category_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_category_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='item_id_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_id_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='item_list_id_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_list_id_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='item_list_name_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_list_name_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='item_name_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_name_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='item_variant_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_item_variant_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='location_id_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_location_id_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='payment_type_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_payment_type_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='price_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_price_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='promotion_id_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_promotion_id_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='promotion_name_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_promotion_name_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='quantity_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_quantity_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='shipping_tier_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_shipping_tier_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='shipping_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_shipping_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='tax_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_tax_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='transaction_id_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_transaction_id_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
        migrations.AlterField(
            model_name='ecommercesnippettemplatega4',
            name='value_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_ga4_value_variable', to='base.ecommercesnippetvariabletemplate'),
        ),
    ]
